services:
  db:
    env_file:
      - env/.env.dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust  # Только для dev!

  pgadmin:
    env_file:
      - env/.env.dev
    ports:
      - "8080:80"
